<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - Omra Taxi</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif; color: #333; margin: 0; padding: 20px; background: #f9f9f9; }
					table { width: 100%; border-collapse: collapse; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; }
					th { background: #0d0d0d; color: #c5a059; text-align: left; padding: 12px 15px; font-weight: 600; text-transform: uppercase; font-size: 12px; letter-spacing: 1px; }
					td { padding: 12px 15px; border-top: 1px solid #eee; font-size: 14px; }
					tr:hover td { background: #fffcf5; }
					a { color: #0d0d0d; text-decoration: none; font-weight: 500; }
					a:hover { color: #c5a059; text-decoration: underline; }
					.header { margin-bottom: 20px; }
					.header h1 { margin: 0 0 5px 0; color: #0d0d0d; }
					.header p { margin: 0; color: #666; font-size: 14px; }
					.priority { color: #666; font-size: 12px; }
				</style>
			</head>
			<body>
				<div class="header">
					<h1>XML Sitemap</h1>
					<p>Generated by Omra Taxi for search engine indexing.</p>
				</div>
				<div id="content">
					<table>
						<tr>
							<th>URL</th>
							<th>Priority</th>
							<th>Change Freq</th>
							<th>Last Modified</th>
						</tr>
						<xsl:for-each select="sitemap:urlset/sitemap:url">
							<tr>
								<td>
									<xsl:variable name="itemURL">
										<xsl:value-of select="sitemap:loc"/>
									</xsl:variable>
									<a href="{$itemURL}">
										<xsl:value-of select="sitemap:loc"/>
									</a>
								</td>
								<td>
									<span class="priority"><xsl:value-of select="sitemap:priority"/></span>
								</td>
								<td>
									<xsl:value-of select="sitemap:changefreq"/>
								</td>
								<td>
									<xsl:value-of select="sitemap:lastmod"/>
								</td>
							</tr>
						</xsl:for-each>
						<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
							<tr>
								<td>
									<xsl:variable name="itemURL">
										<xsl:value-of select="sitemap:loc"/>
									</xsl:variable>
									<a href="{$itemURL}">
										<xsl:value-of select="sitemap:loc"/>
									</a>
								</td>
								<td colspan="3">Sitemap Index File</td>
							</tr>
						</xsl:for-each>
					</table>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
