/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicChar123LocaleChar125RouteImport } from './routes/_public.{-$locale}'
import { Route as PublicChar123LocaleChar125IndexRouteImport } from './routes/_public.{-$locale}.index'
import { Route as PublicChar123LocaleChar125TermsRouteImport } from './routes/_public.{-$locale}.terms'
import { Route as PublicChar123LocaleChar125ServicesRouteImport } from './routes/_public.{-$locale}.services'
import { Route as PublicChar123LocaleChar125RefundRouteImport } from './routes/_public.{-$locale}.refund'
import { Route as PublicChar123LocaleChar125PrivacyRouteImport } from './routes/_public.{-$locale}.privacy'
import { Route as PublicChar123LocaleChar125PricingRouteImport } from './routes/_public.{-$locale}.pricing'
import { Route as PublicChar123LocaleChar125FleetRouteImport } from './routes/_public.{-$locale}.fleet'
import { Route as PublicChar123LocaleChar125FaqRouteImport } from './routes/_public.{-$locale}.faq'
import { Route as PublicChar123LocaleChar125ContactRouteImport } from './routes/_public.{-$locale}.contact'
import { Route as PublicChar123LocaleChar125CancellationRouteImport } from './routes/_public.{-$locale}.cancellation'
import { Route as PublicChar123LocaleChar125BlogRouteImport } from './routes/_public.{-$locale}.blog'
import { Route as PublicChar123LocaleChar125AirportTransfersRouteImport } from './routes/_public.{-$locale}.airport-transfers'
import { Route as PublicChar123LocaleChar125AboutRouteImport } from './routes/_public.{-$locale}.about'
import { Route as AuthenticatedAdminWhatsappTemplatesRouteImport } from './routes/_authenticated/admin.whatsapp-templates'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin.testimonials'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminRoutesRouteImport } from './routes/_authenticated/admin.routes'
import { Route as AuthenticatedAdminRoutePagesRouteImport } from './routes/_authenticated/admin.route-pages'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminRefundsRouteImport } from './routes/_authenticated/admin.refunds'
import { Route as AuthenticatedAdminPromotionsRouteImport } from './routes/_authenticated/admin.promotions'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin.pricing'
import { Route as AuthenticatedAdminPayrollRouteImport } from './routes/_authenticated/admin.payroll'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminOperationsRouteImport } from './routes/_authenticated/admin.operations'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminMenusRouteImport } from './routes/_authenticated/admin.menus'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminMaintenanceRouteImport } from './routes/_authenticated/admin.maintenance'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin.homepage'
import { Route as AuthenticatedAdminHeroRouteImport } from './routes/_authenticated/admin.hero'
import { Route as AuthenticatedAdminFleetDashboardRouteImport } from './routes/_authenticated/admin.fleet-dashboard'
import { Route as AuthenticatedAdminFleetRouteImport } from './routes/_authenticated/admin.fleet'
import { Route as AuthenticatedAdminFinanceSettingsRouteImport } from './routes/_authenticated/admin.finance-settings'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin.faqs'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated/admin.expenses'
import { Route as AuthenticatedAdminErrorsRouteImport } from './routes/_authenticated/admin.errors'
import { Route as AuthenticatedAdminDriversRouteImport } from './routes/_authenticated/admin.drivers'
import { Route as AuthenticatedAdminDispatchRouteImport } from './routes/_authenticated/admin.dispatch'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminCorporateRouteImport } from './routes/_authenticated/admin.corporate'
import { Route as AuthenticatedAdminContactsRouteImport } from './routes/_authenticated/admin.contacts'
import { Route as AuthenticatedAdminCitiesRouteImport } from './routes/_authenticated/admin.cities'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAirportsRouteImport } from './routes/_authenticated/admin.airports'
import { Route as AuthenticatedAdminAiAssistantRouteImport } from './routes/_authenticated/admin.ai-assistant'
import { Route as PublicChar123LocaleChar125ServicesSlugRouteImport } from './routes/_public.{-$locale}.services.$slug'
import { Route as PublicChar123LocaleChar125RoutesSlugRouteImport } from './routes/_public.{-$locale}.routes.$slug'
import { Route as PublicChar123LocaleChar125PSlugRouteImport } from './routes/_public.{-$locale}.p.$slug'
import { Route as PublicChar123LocaleChar125FleetSlugRouteImport } from './routes/_public.{-$locale}.fleet.$slug'
import { Route as PublicChar123LocaleChar125CitiesSlugRouteImport } from './routes/_public.{-$locale}.cities.$slug'
import { Route as PublicChar123LocaleChar125BlogSlugRouteImport } from './routes/_public.{-$locale}.blog.$slug'
import { Route as PublicChar123LocaleChar125AirportsSlugRouteImport } from './routes/_public.{-$locale}.airports.$slug'
import { Route as AuthenticatedAdminInvoicesIdRouteImport } from './routes/_authenticated/admin.invoices.$id'
import { Route as AuthenticatedAdminFleetIdRouteImport } from './routes/_authenticated/admin.fleet.$id'
import { Route as AuthenticatedAdminDriversIdRouteImport } from './routes/_authenticated/admin.drivers.$id'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin.customers.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicChar123LocaleChar125Route =
  PublicChar123LocaleChar125RouteImport.update({
    id: '/_public/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicChar123LocaleChar125IndexRoute =
  PublicChar123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125TermsRoute =
  PublicChar123LocaleChar125TermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125ServicesRoute =
  PublicChar123LocaleChar125ServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125RefundRoute =
  PublicChar123LocaleChar125RefundRouteImport.update({
    id: '/refund',
    path: '/refund',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125PrivacyRoute =
  PublicChar123LocaleChar125PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125PricingRoute =
  PublicChar123LocaleChar125PricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125FleetRoute =
  PublicChar123LocaleChar125FleetRouteImport.update({
    id: '/fleet',
    path: '/fleet',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125FaqRoute =
  PublicChar123LocaleChar125FaqRouteImport.update({
    id: '/faq',
    path: '/faq',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125ContactRoute =
  PublicChar123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125CancellationRoute =
  PublicChar123LocaleChar125CancellationRouteImport.update({
    id: '/cancellation',
    path: '/cancellation',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125BlogRoute =
  PublicChar123LocaleChar125BlogRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125AirportTransfersRoute =
  PublicChar123LocaleChar125AirportTransfersRouteImport.update({
    id: '/airport-transfers',
    path: '/airport-transfers',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125AboutRoute =
  PublicChar123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const AuthenticatedAdminWhatsappTemplatesRoute =
  AuthenticatedAdminWhatsappTemplatesRouteImport.update({
    id: '/admin/whatsapp-templates',
    path: '/admin/whatsapp-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/admin/testimonials',
    path: '/admin/testimonials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/admin/services',
    path: '/admin/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoutesRoute =
  AuthenticatedAdminRoutesRouteImport.update({
    id: '/admin/routes',
    path: '/admin/routes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoutePagesRoute =
  AuthenticatedAdminRoutePagesRouteImport.update({
    id: '/admin/route-pages',
    path: '/admin/route-pages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRefundsRoute =
  AuthenticatedAdminRefundsRouteImport.update({
    id: '/admin/refunds',
    path: '/admin/refunds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPromotionsRoute =
  AuthenticatedAdminPromotionsRouteImport.update({
    id: '/admin/promotions',
    path: '/admin/promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/admin/pricing',
    path: '/admin/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPayrollRoute =
  AuthenticatedAdminPayrollRouteImport.update({
    id: '/admin/payroll',
    path: '/admin/payroll',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/admin/partners',
    path: '/admin/partners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOperationsRoute =
  AuthenticatedAdminOperationsRouteImport.update({
    id: '/admin/operations',
    path: '/admin/operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMenusRoute = AuthenticatedAdminMenusRouteImport.update({
  id: '/admin/menus',
  path: '/admin/menus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMaintenanceRoute =
  AuthenticatedAdminMaintenanceRouteImport.update({
    id: '/admin/maintenance',
    path: '/admin/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/admin/invoices',
    path: '/admin/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/admin/homepage',
    path: '/admin/homepage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHeroRoute = AuthenticatedAdminHeroRouteImport.update({
  id: '/admin/hero',
  path: '/admin/hero',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFleetDashboardRoute =
  AuthenticatedAdminFleetDashboardRouteImport.update({
    id: '/admin/fleet-dashboard',
    path: '/admin/fleet-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFleetRoute = AuthenticatedAdminFleetRouteImport.update({
  id: '/admin/fleet',
  path: '/admin/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFinanceSettingsRoute =
  AuthenticatedAdminFinanceSettingsRouteImport.update({
    id: '/admin/finance-settings',
    path: '/admin/finance-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/admin/finance',
    path: '/admin/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/admin/faqs',
  path: '/admin/faqs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/admin/expenses',
    path: '/admin/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminErrorsRoute =
  AuthenticatedAdminErrorsRouteImport.update({
    id: '/admin/errors',
    path: '/admin/errors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDriversRoute =
  AuthenticatedAdminDriversRouteImport.update({
    id: '/admin/drivers',
    path: '/admin/drivers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDispatchRoute =
  AuthenticatedAdminDispatchRouteImport.update({
    id: '/admin/dispatch',
    path: '/admin/dispatch',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/admin/customers',
    path: '/admin/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/admin/coupons',
    path: '/admin/coupons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCorporateRoute =
  AuthenticatedAdminCorporateRouteImport.update({
    id: '/admin/corporate',
    path: '/admin/corporate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContactsRoute =
  AuthenticatedAdminContactsRouteImport.update({
    id: '/admin/contacts',
    path: '/admin/contacts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCitiesRoute =
  AuthenticatedAdminCitiesRouteImport.update({
    id: '/admin/cities',
    path: '/admin/cities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/admin/bookings',
    path: '/admin/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/admin/backup',
    path: '/admin/backup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAirportsRoute =
  AuthenticatedAdminAirportsRouteImport.update({
    id: '/admin/airports',
    path: '/admin/airports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAiAssistantRoute =
  AuthenticatedAdminAiAssistantRouteImport.update({
    id: '/admin/ai-assistant',
    path: '/admin/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicChar123LocaleChar125ServicesSlugRoute =
  PublicChar123LocaleChar125ServicesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PublicChar123LocaleChar125ServicesRoute,
  } as any)
const PublicChar123LocaleChar125RoutesSlugRoute =
  PublicChar123LocaleChar125RoutesSlugRouteImport.update({
    id: '/routes/$slug',
    path: '/routes/$slug',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125PSlugRoute =
  PublicChar123LocaleChar125PSlugRouteImport.update({
    id: '/p/$slug',
    path: '/p/$slug',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125FleetSlugRoute =
  PublicChar123LocaleChar125FleetSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PublicChar123LocaleChar125FleetRoute,
  } as any)
const PublicChar123LocaleChar125CitiesSlugRoute =
  PublicChar123LocaleChar125CitiesSlugRouteImport.update({
    id: '/cities/$slug',
    path: '/cities/$slug',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const PublicChar123LocaleChar125BlogSlugRoute =
  PublicChar123LocaleChar125BlogSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => PublicChar123LocaleChar125BlogRoute,
  } as any)
const PublicChar123LocaleChar125AirportsSlugRoute =
  PublicChar123LocaleChar125AirportsSlugRouteImport.update({
    id: '/airports/$slug',
    path: '/airports/$slug',
    getParentRoute: () => PublicChar123LocaleChar125Route,
  } as any)
const AuthenticatedAdminInvoicesIdRoute =
  AuthenticatedAdminInvoicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminInvoicesRoute,
  } as any)
const AuthenticatedAdminFleetIdRoute =
  AuthenticatedAdminFleetIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminFleetRoute,
  } as any)
const AuthenticatedAdminDriversIdRoute =
  AuthenticatedAdminDriversIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminDriversRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof PublicChar123LocaleChar125RouteWithChildren
  '/admin/ai-assistant': typeof AuthenticatedAdminAiAssistantRoute
  '/admin/airports': typeof AuthenticatedAdminAirportsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/corporate': typeof AuthenticatedAdminCorporateRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRouteWithChildren
  '/admin/errors': typeof AuthenticatedAdminErrorsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/finance-settings': typeof AuthenticatedAdminFinanceSettingsRoute
  '/admin/fleet': typeof AuthenticatedAdminFleetRouteWithChildren
  '/admin/fleet-dashboard': typeof AuthenticatedAdminFleetDashboardRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/menus': typeof AuthenticatedAdminMenusRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/route-pages': typeof AuthenticatedAdminRoutePagesRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/whatsapp-templates': typeof AuthenticatedAdminWhatsappTemplatesRoute
  '/{-$locale}/about': typeof PublicChar123LocaleChar125AboutRoute
  '/{-$locale}/airport-transfers': typeof PublicChar123LocaleChar125AirportTransfersRoute
  '/{-$locale}/blog': typeof PublicChar123LocaleChar125BlogRouteWithChildren
  '/{-$locale}/cancellation': typeof PublicChar123LocaleChar125CancellationRoute
  '/{-$locale}/contact': typeof PublicChar123LocaleChar125ContactRoute
  '/{-$locale}/faq': typeof PublicChar123LocaleChar125FaqRoute
  '/{-$locale}/fleet': typeof PublicChar123LocaleChar125FleetRouteWithChildren
  '/{-$locale}/pricing': typeof PublicChar123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof PublicChar123LocaleChar125PrivacyRoute
  '/{-$locale}/refund': typeof PublicChar123LocaleChar125RefundRoute
  '/{-$locale}/services': typeof PublicChar123LocaleChar125ServicesRouteWithChildren
  '/{-$locale}/terms': typeof PublicChar123LocaleChar125TermsRoute
  '/{-$locale}/': typeof PublicChar123LocaleChar125IndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/drivers/$id': typeof AuthenticatedAdminDriversIdRoute
  '/admin/fleet/$id': typeof AuthenticatedAdminFleetIdRoute
  '/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
  '/{-$locale}/airports/$slug': typeof PublicChar123LocaleChar125AirportsSlugRoute
  '/{-$locale}/blog/$slug': typeof PublicChar123LocaleChar125BlogSlugRoute
  '/{-$locale}/cities/$slug': typeof PublicChar123LocaleChar125CitiesSlugRoute
  '/{-$locale}/fleet/$slug': typeof PublicChar123LocaleChar125FleetSlugRoute
  '/{-$locale}/p/$slug': typeof PublicChar123LocaleChar125PSlugRoute
  '/{-$locale}/routes/$slug': typeof PublicChar123LocaleChar125RoutesSlugRoute
  '/{-$locale}/services/$slug': typeof PublicChar123LocaleChar125ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ai-assistant': typeof AuthenticatedAdminAiAssistantRoute
  '/admin/airports': typeof AuthenticatedAdminAirportsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/corporate': typeof AuthenticatedAdminCorporateRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRouteWithChildren
  '/admin/errors': typeof AuthenticatedAdminErrorsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/finance-settings': typeof AuthenticatedAdminFinanceSettingsRoute
  '/admin/fleet': typeof AuthenticatedAdminFleetRouteWithChildren
  '/admin/fleet-dashboard': typeof AuthenticatedAdminFleetDashboardRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/menus': typeof AuthenticatedAdminMenusRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/route-pages': typeof AuthenticatedAdminRoutePagesRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/whatsapp-templates': typeof AuthenticatedAdminWhatsappTemplatesRoute
  '/{-$locale}/about': typeof PublicChar123LocaleChar125AboutRoute
  '/{-$locale}/airport-transfers': typeof PublicChar123LocaleChar125AirportTransfersRoute
  '/{-$locale}/blog': typeof PublicChar123LocaleChar125BlogRouteWithChildren
  '/{-$locale}/cancellation': typeof PublicChar123LocaleChar125CancellationRoute
  '/{-$locale}/contact': typeof PublicChar123LocaleChar125ContactRoute
  '/{-$locale}/faq': typeof PublicChar123LocaleChar125FaqRoute
  '/{-$locale}/fleet': typeof PublicChar123LocaleChar125FleetRouteWithChildren
  '/{-$locale}/pricing': typeof PublicChar123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof PublicChar123LocaleChar125PrivacyRoute
  '/{-$locale}/refund': typeof PublicChar123LocaleChar125RefundRoute
  '/{-$locale}/services': typeof PublicChar123LocaleChar125ServicesRouteWithChildren
  '/{-$locale}/terms': typeof PublicChar123LocaleChar125TermsRoute
  '/{-$locale}': typeof PublicChar123LocaleChar125IndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/drivers/$id': typeof AuthenticatedAdminDriversIdRoute
  '/admin/fleet/$id': typeof AuthenticatedAdminFleetIdRoute
  '/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
  '/{-$locale}/airports/$slug': typeof PublicChar123LocaleChar125AirportsSlugRoute
  '/{-$locale}/blog/$slug': typeof PublicChar123LocaleChar125BlogSlugRoute
  '/{-$locale}/cities/$slug': typeof PublicChar123LocaleChar125CitiesSlugRoute
  '/{-$locale}/fleet/$slug': typeof PublicChar123LocaleChar125FleetSlugRoute
  '/{-$locale}/p/$slug': typeof PublicChar123LocaleChar125PSlugRoute
  '/{-$locale}/routes/$slug': typeof PublicChar123LocaleChar125RoutesSlugRoute
  '/{-$locale}/services/$slug': typeof PublicChar123LocaleChar125ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/{-$locale}': typeof PublicChar123LocaleChar125RouteWithChildren
  '/_authenticated/admin/ai-assistant': typeof AuthenticatedAdminAiAssistantRoute
  '/_authenticated/admin/airports': typeof AuthenticatedAdminAirportsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/_authenticated/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/_authenticated/admin/corporate': typeof AuthenticatedAdminCorporateRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/_authenticated/admin/drivers': typeof AuthenticatedAdminDriversRouteWithChildren
  '/_authenticated/admin/errors': typeof AuthenticatedAdminErrorsRoute
  '/_authenticated/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/finance-settings': typeof AuthenticatedAdminFinanceSettingsRoute
  '/_authenticated/admin/fleet': typeof AuthenticatedAdminFleetRouteWithChildren
  '/_authenticated/admin/fleet-dashboard': typeof AuthenticatedAdminFleetDashboardRoute
  '/_authenticated/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/_authenticated/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/menus': typeof AuthenticatedAdminMenusRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/_authenticated/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/route-pages': typeof AuthenticatedAdminRoutePagesRoute
  '/_authenticated/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/whatsapp-templates': typeof AuthenticatedAdminWhatsappTemplatesRoute
  '/_public/{-$locale}/about': typeof PublicChar123LocaleChar125AboutRoute
  '/_public/{-$locale}/airport-transfers': typeof PublicChar123LocaleChar125AirportTransfersRoute
  '/_public/{-$locale}/blog': typeof PublicChar123LocaleChar125BlogRouteWithChildren
  '/_public/{-$locale}/cancellation': typeof PublicChar123LocaleChar125CancellationRoute
  '/_public/{-$locale}/contact': typeof PublicChar123LocaleChar125ContactRoute
  '/_public/{-$locale}/faq': typeof PublicChar123LocaleChar125FaqRoute
  '/_public/{-$locale}/fleet': typeof PublicChar123LocaleChar125FleetRouteWithChildren
  '/_public/{-$locale}/pricing': typeof PublicChar123LocaleChar125PricingRoute
  '/_public/{-$locale}/privacy': typeof PublicChar123LocaleChar125PrivacyRoute
  '/_public/{-$locale}/refund': typeof PublicChar123LocaleChar125RefundRoute
  '/_public/{-$locale}/services': typeof PublicChar123LocaleChar125ServicesRouteWithChildren
  '/_public/{-$locale}/terms': typeof PublicChar123LocaleChar125TermsRoute
  '/_public/{-$locale}/': typeof PublicChar123LocaleChar125IndexRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/drivers/$id': typeof AuthenticatedAdminDriversIdRoute
  '/_authenticated/admin/fleet/$id': typeof AuthenticatedAdminFleetIdRoute
  '/_authenticated/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
  '/_public/{-$locale}/airports/$slug': typeof PublicChar123LocaleChar125AirportsSlugRoute
  '/_public/{-$locale}/blog/$slug': typeof PublicChar123LocaleChar125BlogSlugRoute
  '/_public/{-$locale}/cities/$slug': typeof PublicChar123LocaleChar125CitiesSlugRoute
  '/_public/{-$locale}/fleet/$slug': typeof PublicChar123LocaleChar125FleetSlugRoute
  '/_public/{-$locale}/p/$slug': typeof PublicChar123LocaleChar125PSlugRoute
  '/_public/{-$locale}/routes/$slug': typeof PublicChar123LocaleChar125RoutesSlugRoute
  '/_public/{-$locale}/services/$slug': typeof PublicChar123LocaleChar125ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/admin/ai-assistant'
    | '/admin/airports'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/cities'
    | '/admin/contacts'
    | '/admin/corporate'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/dispatch'
    | '/admin/drivers'
    | '/admin/errors'
    | '/admin/expenses'
    | '/admin/faqs'
    | '/admin/finance'
    | '/admin/finance-settings'
    | '/admin/fleet'
    | '/admin/fleet-dashboard'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/invoices'
    | '/admin/maintenance'
    | '/admin/media'
    | '/admin/menus'
    | '/admin/notifications'
    | '/admin/operations'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/payroll'
    | '/admin/pricing'
    | '/admin/promotions'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/route-pages'
    | '/admin/routes'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/whatsapp-templates'
    | '/{-$locale}/about'
    | '/{-$locale}/airport-transfers'
    | '/{-$locale}/blog'
    | '/{-$locale}/cancellation'
    | '/{-$locale}/contact'
    | '/{-$locale}/faq'
    | '/{-$locale}/fleet'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/refund'
    | '/{-$locale}/services'
    | '/{-$locale}/terms'
    | '/{-$locale}/'
    | '/admin/customers/$id'
    | '/admin/drivers/$id'
    | '/admin/fleet/$id'
    | '/admin/invoices/$id'
    | '/{-$locale}/airports/$slug'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/cities/$slug'
    | '/{-$locale}/fleet/$slug'
    | '/{-$locale}/p/$slug'
    | '/{-$locale}/routes/$slug'
    | '/{-$locale}/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/ai-assistant'
    | '/admin/airports'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/cities'
    | '/admin/contacts'
    | '/admin/corporate'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/dispatch'
    | '/admin/drivers'
    | '/admin/errors'
    | '/admin/expenses'
    | '/admin/faqs'
    | '/admin/finance'
    | '/admin/finance-settings'
    | '/admin/fleet'
    | '/admin/fleet-dashboard'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/invoices'
    | '/admin/maintenance'
    | '/admin/media'
    | '/admin/menus'
    | '/admin/notifications'
    | '/admin/operations'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/payroll'
    | '/admin/pricing'
    | '/admin/promotions'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/route-pages'
    | '/admin/routes'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/whatsapp-templates'
    | '/{-$locale}/about'
    | '/{-$locale}/airport-transfers'
    | '/{-$locale}/blog'
    | '/{-$locale}/cancellation'
    | '/{-$locale}/contact'
    | '/{-$locale}/faq'
    | '/{-$locale}/fleet'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/refund'
    | '/{-$locale}/services'
    | '/{-$locale}/terms'
    | '/{-$locale}'
    | '/admin/customers/$id'
    | '/admin/drivers/$id'
    | '/admin/fleet/$id'
    | '/admin/invoices/$id'
    | '/{-$locale}/airports/$slug'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/cities/$slug'
    | '/{-$locale}/fleet/$slug'
    | '/{-$locale}/p/$slug'
    | '/{-$locale}/routes/$slug'
    | '/{-$locale}/services/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_public/{-$locale}'
    | '/_authenticated/admin/ai-assistant'
    | '/_authenticated/admin/airports'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/cities'
    | '/_authenticated/admin/contacts'
    | '/_authenticated/admin/corporate'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/dispatch'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/errors'
    | '/_authenticated/admin/expenses'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/finance-settings'
    | '/_authenticated/admin/fleet'
    | '/_authenticated/admin/fleet-dashboard'
    | '/_authenticated/admin/hero'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/maintenance'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/menus'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/operations'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/payroll'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/promotions'
    | '/_authenticated/admin/refunds'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/route-pages'
    | '/_authenticated/admin/routes'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/whatsapp-templates'
    | '/_public/{-$locale}/about'
    | '/_public/{-$locale}/airport-transfers'
    | '/_public/{-$locale}/blog'
    | '/_public/{-$locale}/cancellation'
    | '/_public/{-$locale}/contact'
    | '/_public/{-$locale}/faq'
    | '/_public/{-$locale}/fleet'
    | '/_public/{-$locale}/pricing'
    | '/_public/{-$locale}/privacy'
    | '/_public/{-$locale}/refund'
    | '/_public/{-$locale}/services'
    | '/_public/{-$locale}/terms'
    | '/_public/{-$locale}/'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/drivers/$id'
    | '/_authenticated/admin/fleet/$id'
    | '/_authenticated/admin/invoices/$id'
    | '/_public/{-$locale}/airports/$slug'
    | '/_public/{-$locale}/blog/$slug'
    | '/_public/{-$locale}/cities/$slug'
    | '/_public/{-$locale}/fleet/$slug'
    | '/_public/{-$locale}/p/$slug'
    | '/_public/{-$locale}/routes/$slug'
    | '/_public/{-$locale}/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PublicChar123LocaleChar125Route: typeof PublicChar123LocaleChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/{-$locale}': {
      id: '/_public/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof PublicChar123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/{-$locale}/': {
      id: '/_public/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof PublicChar123LocaleChar125IndexRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/terms': {
      id: '/_public/{-$locale}/terms'
      path: '/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof PublicChar123LocaleChar125TermsRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/services': {
      id: '/_public/{-$locale}/services'
      path: '/services'
      fullPath: '/{-$locale}/services'
      preLoaderRoute: typeof PublicChar123LocaleChar125ServicesRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/refund': {
      id: '/_public/{-$locale}/refund'
      path: '/refund'
      fullPath: '/{-$locale}/refund'
      preLoaderRoute: typeof PublicChar123LocaleChar125RefundRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/privacy': {
      id: '/_public/{-$locale}/privacy'
      path: '/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof PublicChar123LocaleChar125PrivacyRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/pricing': {
      id: '/_public/{-$locale}/pricing'
      path: '/pricing'
      fullPath: '/{-$locale}/pricing'
      preLoaderRoute: typeof PublicChar123LocaleChar125PricingRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/fleet': {
      id: '/_public/{-$locale}/fleet'
      path: '/fleet'
      fullPath: '/{-$locale}/fleet'
      preLoaderRoute: typeof PublicChar123LocaleChar125FleetRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/faq': {
      id: '/_public/{-$locale}/faq'
      path: '/faq'
      fullPath: '/{-$locale}/faq'
      preLoaderRoute: typeof PublicChar123LocaleChar125FaqRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/contact': {
      id: '/_public/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof PublicChar123LocaleChar125ContactRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/cancellation': {
      id: '/_public/{-$locale}/cancellation'
      path: '/cancellation'
      fullPath: '/{-$locale}/cancellation'
      preLoaderRoute: typeof PublicChar123LocaleChar125CancellationRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/blog': {
      id: '/_public/{-$locale}/blog'
      path: '/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof PublicChar123LocaleChar125BlogRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/airport-transfers': {
      id: '/_public/{-$locale}/airport-transfers'
      path: '/airport-transfers'
      fullPath: '/{-$locale}/airport-transfers'
      preLoaderRoute: typeof PublicChar123LocaleChar125AirportTransfersRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/about': {
      id: '/_public/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof PublicChar123LocaleChar125AboutRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_authenticated/admin/whatsapp-templates': {
      id: '/_authenticated/admin/whatsapp-templates'
      path: '/admin/whatsapp-templates'
      fullPath: '/admin/whatsapp-templates'
      preLoaderRoute: typeof AuthenticatedAdminWhatsappTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/routes': {
      id: '/_authenticated/admin/routes'
      path: '/admin/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AuthenticatedAdminRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/route-pages': {
      id: '/_authenticated/admin/route-pages'
      path: '/admin/route-pages'
      fullPath: '/admin/route-pages'
      preLoaderRoute: typeof AuthenticatedAdminRoutePagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/refunds': {
      id: '/_authenticated/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AuthenticatedAdminRefundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/promotions': {
      id: '/_authenticated/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AuthenticatedAdminPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payroll': {
      id: '/_authenticated/admin/payroll'
      path: '/admin/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AuthenticatedAdminPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/operations': {
      id: '/_authenticated/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AuthenticatedAdminOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/menus': {
      id: '/_authenticated/admin/menus'
      path: '/admin/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AuthenticatedAdminMenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/maintenance': {
      id: '/_authenticated/admin/maintenance'
      path: '/admin/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/hero': {
      id: '/_authenticated/admin/hero'
      path: '/admin/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AuthenticatedAdminHeroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fleet-dashboard': {
      id: '/_authenticated/admin/fleet-dashboard'
      path: '/admin/fleet-dashboard'
      fullPath: '/admin/fleet-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminFleetDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fleet': {
      id: '/_authenticated/admin/fleet'
      path: '/admin/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AuthenticatedAdminFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/finance-settings': {
      id: '/_authenticated/admin/finance-settings'
      path: '/admin/finance-settings'
      fullPath: '/admin/finance-settings'
      preLoaderRoute: typeof AuthenticatedAdminFinanceSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/admin/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/expenses': {
      id: '/_authenticated/admin/expenses'
      path: '/admin/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/errors': {
      id: '/_authenticated/admin/errors'
      path: '/admin/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AuthenticatedAdminErrorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/drivers': {
      id: '/_authenticated/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AuthenticatedAdminDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dispatch': {
      id: '/_authenticated/admin/dispatch'
      path: '/admin/dispatch'
      fullPath: '/admin/dispatch'
      preLoaderRoute: typeof AuthenticatedAdminDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/corporate': {
      id: '/_authenticated/admin/corporate'
      path: '/admin/corporate'
      fullPath: '/admin/corporate'
      preLoaderRoute: typeof AuthenticatedAdminCorporateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contacts': {
      id: '/_authenticated/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AuthenticatedAdminContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cities': {
      id: '/_authenticated/admin/cities'
      path: '/admin/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AuthenticatedAdminCitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/admin/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/airports': {
      id: '/_authenticated/admin/airports'
      path: '/admin/airports'
      fullPath: '/admin/airports'
      preLoaderRoute: typeof AuthenticatedAdminAirportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ai-assistant': {
      id: '/_authenticated/admin/ai-assistant'
      path: '/admin/ai-assistant'
      fullPath: '/admin/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAdminAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/{-$locale}/services/$slug': {
      id: '/_public/{-$locale}/services/$slug'
      path: '/$slug'
      fullPath: '/{-$locale}/services/$slug'
      preLoaderRoute: typeof PublicChar123LocaleChar125ServicesSlugRouteImport
      parentRoute: typeof PublicChar123LocaleChar125ServicesRoute
    }
    '/_public/{-$locale}/routes/$slug': {
      id: '/_public/{-$locale}/routes/$slug'
      path: '/routes/$slug'
      fullPath: '/{-$locale}/routes/$slug'
      preLoaderRoute: typeof PublicChar123LocaleChar125RoutesSlugRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/p/$slug': {
      id: '/_public/{-$locale}/p/$slug'
      path: '/p/$slug'
      fullPath: '/{-$locale}/p/$slug'
      preLoaderRoute: typeof PublicChar123LocaleChar125PSlugRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/fleet/$slug': {
      id: '/_public/{-$locale}/fleet/$slug'
      path: '/$slug'
      fullPath: '/{-$locale}/fleet/$slug'
      preLoaderRoute: typeof PublicChar123LocaleChar125FleetSlugRouteImport
      parentRoute: typeof PublicChar123LocaleChar125FleetRoute
    }
    '/_public/{-$locale}/cities/$slug': {
      id: '/_public/{-$locale}/cities/$slug'
      path: '/cities/$slug'
      fullPath: '/{-$locale}/cities/$slug'
      preLoaderRoute: typeof PublicChar123LocaleChar125CitiesSlugRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_public/{-$locale}/blog/$slug': {
      id: '/_public/{-$locale}/blog/$slug'
      path: '/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof PublicChar123LocaleChar125BlogSlugRouteImport
      parentRoute: typeof PublicChar123LocaleChar125BlogRoute
    }
    '/_public/{-$locale}/airports/$slug': {
      id: '/_public/{-$locale}/airports/$slug'
      path: '/airports/$slug'
      fullPath: '/{-$locale}/airports/$slug'
      preLoaderRoute: typeof PublicChar123LocaleChar125AirportsSlugRouteImport
      parentRoute: typeof PublicChar123LocaleChar125Route
    }
    '/_authenticated/admin/invoices/$id': {
      id: '/_authenticated/admin/invoices/$id'
      path: '/$id'
      fullPath: '/admin/invoices/$id'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedAdminInvoicesRoute
    }
    '/_authenticated/admin/fleet/$id': {
      id: '/_authenticated/admin/fleet/$id'
      path: '/$id'
      fullPath: '/admin/fleet/$id'
      preLoaderRoute: typeof AuthenticatedAdminFleetIdRouteImport
      parentRoute: typeof AuthenticatedAdminFleetRoute
    }
    '/_authenticated/admin/drivers/$id': {
      id: '/_authenticated/admin/drivers/$id'
      path: '/$id'
      fullPath: '/admin/drivers/$id'
      preLoaderRoute: typeof AuthenticatedAdminDriversIdRouteImport
      parentRoute: typeof AuthenticatedAdminDriversRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
  }
}

interface AuthenticatedAdminCustomersRouteChildren {
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
}

const AuthenticatedAdminCustomersRouteChildren: AuthenticatedAdminCustomersRouteChildren =
  {
    AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  }

const AuthenticatedAdminCustomersRouteWithChildren =
  AuthenticatedAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminDriversRouteChildren {
  AuthenticatedAdminDriversIdRoute: typeof AuthenticatedAdminDriversIdRoute
}

const AuthenticatedAdminDriversRouteChildren: AuthenticatedAdminDriversRouteChildren =
  {
    AuthenticatedAdminDriversIdRoute: AuthenticatedAdminDriversIdRoute,
  }

const AuthenticatedAdminDriversRouteWithChildren =
  AuthenticatedAdminDriversRoute._addFileChildren(
    AuthenticatedAdminDriversRouteChildren,
  )

interface AuthenticatedAdminFleetRouteChildren {
  AuthenticatedAdminFleetIdRoute: typeof AuthenticatedAdminFleetIdRoute
}

const AuthenticatedAdminFleetRouteChildren: AuthenticatedAdminFleetRouteChildren =
  {
    AuthenticatedAdminFleetIdRoute: AuthenticatedAdminFleetIdRoute,
  }

const AuthenticatedAdminFleetRouteWithChildren =
  AuthenticatedAdminFleetRoute._addFileChildren(
    AuthenticatedAdminFleetRouteChildren,
  )

interface AuthenticatedAdminInvoicesRouteChildren {
  AuthenticatedAdminInvoicesIdRoute: typeof AuthenticatedAdminInvoicesIdRoute
}

const AuthenticatedAdminInvoicesRouteChildren: AuthenticatedAdminInvoicesRouteChildren =
  {
    AuthenticatedAdminInvoicesIdRoute: AuthenticatedAdminInvoicesIdRoute,
  }

const AuthenticatedAdminInvoicesRouteWithChildren =
  AuthenticatedAdminInvoicesRoute._addFileChildren(
    AuthenticatedAdminInvoicesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAiAssistantRoute: typeof AuthenticatedAdminAiAssistantRoute
  AuthenticatedAdminAirportsRoute: typeof AuthenticatedAdminAirportsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCitiesRoute: typeof AuthenticatedAdminCitiesRoute
  AuthenticatedAdminContactsRoute: typeof AuthenticatedAdminContactsRoute
  AuthenticatedAdminCorporateRoute: typeof AuthenticatedAdminCorporateRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRouteWithChildren
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDispatchRoute: typeof AuthenticatedAdminDispatchRoute
  AuthenticatedAdminDriversRoute: typeof AuthenticatedAdminDriversRouteWithChildren
  AuthenticatedAdminErrorsRoute: typeof AuthenticatedAdminErrorsRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminFinanceSettingsRoute: typeof AuthenticatedAdminFinanceSettingsRoute
  AuthenticatedAdminFleetRoute: typeof AuthenticatedAdminFleetRouteWithChildren
  AuthenticatedAdminFleetDashboardRoute: typeof AuthenticatedAdminFleetDashboardRoute
  AuthenticatedAdminHeroRoute: typeof AuthenticatedAdminHeroRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRouteWithChildren
  AuthenticatedAdminMaintenanceRoute: typeof AuthenticatedAdminMaintenanceRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMenusRoute: typeof AuthenticatedAdminMenusRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOperationsRoute: typeof AuthenticatedAdminOperationsRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPayrollRoute: typeof AuthenticatedAdminPayrollRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminPromotionsRoute: typeof AuthenticatedAdminPromotionsRoute
  AuthenticatedAdminRefundsRoute: typeof AuthenticatedAdminRefundsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminRoutePagesRoute: typeof AuthenticatedAdminRoutePagesRoute
  AuthenticatedAdminRoutesRoute: typeof AuthenticatedAdminRoutesRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWhatsappTemplatesRoute: typeof AuthenticatedAdminWhatsappTemplatesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAiAssistantRoute: AuthenticatedAdminAiAssistantRoute,
  AuthenticatedAdminAirportsRoute: AuthenticatedAdminAirportsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCitiesRoute: AuthenticatedAdminCitiesRoute,
  AuthenticatedAdminContactsRoute: AuthenticatedAdminContactsRoute,
  AuthenticatedAdminCorporateRoute: AuthenticatedAdminCorporateRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminCustomersRoute:
    AuthenticatedAdminCustomersRouteWithChildren,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDispatchRoute: AuthenticatedAdminDispatchRoute,
  AuthenticatedAdminDriversRoute: AuthenticatedAdminDriversRouteWithChildren,
  AuthenticatedAdminErrorsRoute: AuthenticatedAdminErrorsRoute,
  AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminFinanceSettingsRoute:
    AuthenticatedAdminFinanceSettingsRoute,
  AuthenticatedAdminFleetRoute: AuthenticatedAdminFleetRouteWithChildren,
  AuthenticatedAdminFleetDashboardRoute: AuthenticatedAdminFleetDashboardRoute,
  AuthenticatedAdminHeroRoute: AuthenticatedAdminHeroRoute,
  AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRouteWithChildren,
  AuthenticatedAdminMaintenanceRoute: AuthenticatedAdminMaintenanceRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminMenusRoute: AuthenticatedAdminMenusRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminOperationsRoute: AuthenticatedAdminOperationsRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPayrollRoute: AuthenticatedAdminPayrollRoute,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
  AuthenticatedAdminPromotionsRoute: AuthenticatedAdminPromotionsRoute,
  AuthenticatedAdminRefundsRoute: AuthenticatedAdminRefundsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminRoutePagesRoute: AuthenticatedAdminRoutePagesRoute,
  AuthenticatedAdminRoutesRoute: AuthenticatedAdminRoutesRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWhatsappTemplatesRoute:
    AuthenticatedAdminWhatsappTemplatesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicChar123LocaleChar125BlogRouteChildren {
  PublicChar123LocaleChar125BlogSlugRoute: typeof PublicChar123LocaleChar125BlogSlugRoute
}

const PublicChar123LocaleChar125BlogRouteChildren: PublicChar123LocaleChar125BlogRouteChildren =
  {
    PublicChar123LocaleChar125BlogSlugRoute:
      PublicChar123LocaleChar125BlogSlugRoute,
  }

const PublicChar123LocaleChar125BlogRouteWithChildren =
  PublicChar123LocaleChar125BlogRoute._addFileChildren(
    PublicChar123LocaleChar125BlogRouteChildren,
  )

interface PublicChar123LocaleChar125FleetRouteChildren {
  PublicChar123LocaleChar125FleetSlugRoute: typeof PublicChar123LocaleChar125FleetSlugRoute
}

const PublicChar123LocaleChar125FleetRouteChildren: PublicChar123LocaleChar125FleetRouteChildren =
  {
    PublicChar123LocaleChar125FleetSlugRoute:
      PublicChar123LocaleChar125FleetSlugRoute,
  }

const PublicChar123LocaleChar125FleetRouteWithChildren =
  PublicChar123LocaleChar125FleetRoute._addFileChildren(
    PublicChar123LocaleChar125FleetRouteChildren,
  )

interface PublicChar123LocaleChar125ServicesRouteChildren {
  PublicChar123LocaleChar125ServicesSlugRoute: typeof PublicChar123LocaleChar125ServicesSlugRoute
}

const PublicChar123LocaleChar125ServicesRouteChildren: PublicChar123LocaleChar125ServicesRouteChildren =
  {
    PublicChar123LocaleChar125ServicesSlugRoute:
      PublicChar123LocaleChar125ServicesSlugRoute,
  }

const PublicChar123LocaleChar125ServicesRouteWithChildren =
  PublicChar123LocaleChar125ServicesRoute._addFileChildren(
    PublicChar123LocaleChar125ServicesRouteChildren,
  )

interface PublicChar123LocaleChar125RouteChildren {
  PublicChar123LocaleChar125AboutRoute: typeof PublicChar123LocaleChar125AboutRoute
  PublicChar123LocaleChar125AirportTransfersRoute: typeof PublicChar123LocaleChar125AirportTransfersRoute
  PublicChar123LocaleChar125BlogRoute: typeof PublicChar123LocaleChar125BlogRouteWithChildren
  PublicChar123LocaleChar125CancellationRoute: typeof PublicChar123LocaleChar125CancellationRoute
  PublicChar123LocaleChar125ContactRoute: typeof PublicChar123LocaleChar125ContactRoute
  PublicChar123LocaleChar125FaqRoute: typeof PublicChar123LocaleChar125FaqRoute
  PublicChar123LocaleChar125FleetRoute: typeof PublicChar123LocaleChar125FleetRouteWithChildren
  PublicChar123LocaleChar125PricingRoute: typeof PublicChar123LocaleChar125PricingRoute
  PublicChar123LocaleChar125PrivacyRoute: typeof PublicChar123LocaleChar125PrivacyRoute
  PublicChar123LocaleChar125RefundRoute: typeof PublicChar123LocaleChar125RefundRoute
  PublicChar123LocaleChar125ServicesRoute: typeof PublicChar123LocaleChar125ServicesRouteWithChildren
  PublicChar123LocaleChar125TermsRoute: typeof PublicChar123LocaleChar125TermsRoute
  PublicChar123LocaleChar125IndexRoute: typeof PublicChar123LocaleChar125IndexRoute
  PublicChar123LocaleChar125AirportsSlugRoute: typeof PublicChar123LocaleChar125AirportsSlugRoute
  PublicChar123LocaleChar125CitiesSlugRoute: typeof PublicChar123LocaleChar125CitiesSlugRoute
  PublicChar123LocaleChar125PSlugRoute: typeof PublicChar123LocaleChar125PSlugRoute
  PublicChar123LocaleChar125RoutesSlugRoute: typeof PublicChar123LocaleChar125RoutesSlugRoute
}

const PublicChar123LocaleChar125RouteChildren: PublicChar123LocaleChar125RouteChildren =
  {
    PublicChar123LocaleChar125AboutRoute: PublicChar123LocaleChar125AboutRoute,
    PublicChar123LocaleChar125AirportTransfersRoute:
      PublicChar123LocaleChar125AirportTransfersRoute,
    PublicChar123LocaleChar125BlogRoute:
      PublicChar123LocaleChar125BlogRouteWithChildren,
    PublicChar123LocaleChar125CancellationRoute:
      PublicChar123LocaleChar125CancellationRoute,
    PublicChar123LocaleChar125ContactRoute:
      PublicChar123LocaleChar125ContactRoute,
    PublicChar123LocaleChar125FaqRoute: PublicChar123LocaleChar125FaqRoute,
    PublicChar123LocaleChar125FleetRoute:
      PublicChar123LocaleChar125FleetRouteWithChildren,
    PublicChar123LocaleChar125PricingRoute:
      PublicChar123LocaleChar125PricingRoute,
    PublicChar123LocaleChar125PrivacyRoute:
      PublicChar123LocaleChar125PrivacyRoute,
    PublicChar123LocaleChar125RefundRoute:
      PublicChar123LocaleChar125RefundRoute,
    PublicChar123LocaleChar125ServicesRoute:
      PublicChar123LocaleChar125ServicesRouteWithChildren,
    PublicChar123LocaleChar125TermsRoute: PublicChar123LocaleChar125TermsRoute,
    PublicChar123LocaleChar125IndexRoute: PublicChar123LocaleChar125IndexRoute,
    PublicChar123LocaleChar125AirportsSlugRoute:
      PublicChar123LocaleChar125AirportsSlugRoute,
    PublicChar123LocaleChar125CitiesSlugRoute:
      PublicChar123LocaleChar125CitiesSlugRoute,
    PublicChar123LocaleChar125PSlugRoute: PublicChar123LocaleChar125PSlugRoute,
    PublicChar123LocaleChar125RoutesSlugRoute:
      PublicChar123LocaleChar125RoutesSlugRoute,
  }

const PublicChar123LocaleChar125RouteWithChildren =
  PublicChar123LocaleChar125Route._addFileChildren(
    PublicChar123LocaleChar125RouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PublicChar123LocaleChar125Route: PublicChar123LocaleChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
