/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicTermsRouteImport } from './routes/_public.terms'
import { Route as PublicServicesRouteImport } from './routes/_public.services'
import { Route as PublicRefundRouteImport } from './routes/_public.refund'
import { Route as PublicPrivacyRouteImport } from './routes/_public.privacy'
import { Route as PublicPricingRouteImport } from './routes/_public.pricing'
import { Route as PublicFleetRouteImport } from './routes/_public.fleet'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicCancellationRouteImport } from './routes/_public.cancellation'
import { Route as PublicBlogRouteImport } from './routes/_public.blog'
import { Route as PublicAirportTransfersRouteImport } from './routes/_public.airport-transfers'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicPSlugRouteImport } from './routes/_public.p.$slug'
import { Route as PublicBlogSlugRouteImport } from './routes/_public.blog.$slug'
import { Route as AuthenticatedAdminWhatsappTemplatesRouteImport } from './routes/_authenticated/admin.whatsapp-templates'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRoutesRouteImport } from './routes/_authenticated/admin.routes'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminRefundsRouteImport } from './routes/_authenticated/admin.refunds'
import { Route as AuthenticatedAdminPromotionsRouteImport } from './routes/_authenticated/admin.promotions'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin.pricing'
import { Route as AuthenticatedAdminPayrollRouteImport } from './routes/_authenticated/admin.payroll'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminOperationsRouteImport } from './routes/_authenticated/admin.operations'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminMaintenanceRouteImport } from './routes/_authenticated/admin.maintenance'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin.homepage'
import { Route as AuthenticatedAdminHeroRouteImport } from './routes/_authenticated/admin.hero'
import { Route as AuthenticatedAdminFleetDashboardRouteImport } from './routes/_authenticated/admin.fleet-dashboard'
import { Route as AuthenticatedAdminFleetRouteImport } from './routes/_authenticated/admin.fleet'
import { Route as AuthenticatedAdminFinanceSettingsRouteImport } from './routes/_authenticated/admin.finance-settings'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin.faqs'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated/admin.expenses'
import { Route as AuthenticatedAdminErrorsRouteImport } from './routes/_authenticated/admin.errors'
import { Route as AuthenticatedAdminDriversRouteImport } from './routes/_authenticated/admin.drivers'
import { Route as AuthenticatedAdminDispatchRouteImport } from './routes/_authenticated/admin.dispatch'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminCorporateRouteImport } from './routes/_authenticated/admin.corporate'
import { Route as AuthenticatedAdminContactsRouteImport } from './routes/_authenticated/admin.contacts'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAiAssistantRouteImport } from './routes/_authenticated/admin.ai-assistant'
import { Route as AuthenticatedAdminInvoicesIdRouteImport } from './routes/_authenticated/admin.invoices.$id'
import { Route as AuthenticatedAdminFleetIdRouteImport } from './routes/_authenticated/admin.fleet.$id'
import { Route as AuthenticatedAdminDriversIdRouteImport } from './routes/_authenticated/admin.drivers.$id'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin.customers.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRefundRoute = PublicRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFleetRoute = PublicFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCancellationRoute = PublicCancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogRoute = PublicBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAirportTransfersRoute = PublicAirportTransfersRouteImport.update({
  id: '/airport-transfers',
  path: '/airport-transfers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPSlugRoute = PublicPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicBlogRoute,
} as any)
const AuthenticatedAdminWhatsappTemplatesRoute =
  AuthenticatedAdminWhatsappTemplatesRouteImport.update({
    id: '/admin/whatsapp-templates',
    path: '/admin/whatsapp-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoutesRoute =
  AuthenticatedAdminRoutesRouteImport.update({
    id: '/admin/routes',
    path: '/admin/routes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRefundsRoute =
  AuthenticatedAdminRefundsRouteImport.update({
    id: '/admin/refunds',
    path: '/admin/refunds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPromotionsRoute =
  AuthenticatedAdminPromotionsRouteImport.update({
    id: '/admin/promotions',
    path: '/admin/promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/admin/pricing',
    path: '/admin/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPayrollRoute =
  AuthenticatedAdminPayrollRouteImport.update({
    id: '/admin/payroll',
    path: '/admin/payroll',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/admin/partners',
    path: '/admin/partners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOperationsRoute =
  AuthenticatedAdminOperationsRouteImport.update({
    id: '/admin/operations',
    path: '/admin/operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMaintenanceRoute =
  AuthenticatedAdminMaintenanceRouteImport.update({
    id: '/admin/maintenance',
    path: '/admin/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/admin/invoices',
    path: '/admin/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/admin/homepage',
    path: '/admin/homepage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHeroRoute = AuthenticatedAdminHeroRouteImport.update({
  id: '/admin/hero',
  path: '/admin/hero',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFleetDashboardRoute =
  AuthenticatedAdminFleetDashboardRouteImport.update({
    id: '/admin/fleet-dashboard',
    path: '/admin/fleet-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFleetRoute = AuthenticatedAdminFleetRouteImport.update({
  id: '/admin/fleet',
  path: '/admin/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFinanceSettingsRoute =
  AuthenticatedAdminFinanceSettingsRouteImport.update({
    id: '/admin/finance-settings',
    path: '/admin/finance-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/admin/finance',
    path: '/admin/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/admin/faqs',
  path: '/admin/faqs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/admin/expenses',
    path: '/admin/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminErrorsRoute =
  AuthenticatedAdminErrorsRouteImport.update({
    id: '/admin/errors',
    path: '/admin/errors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDriversRoute =
  AuthenticatedAdminDriversRouteImport.update({
    id: '/admin/drivers',
    path: '/admin/drivers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDispatchRoute =
  AuthenticatedAdminDispatchRouteImport.update({
    id: '/admin/dispatch',
    path: '/admin/dispatch',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/admin/customers',
    path: '/admin/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/admin/coupons',
    path: '/admin/coupons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCorporateRoute =
  AuthenticatedAdminCorporateRouteImport.update({
    id: '/admin/corporate',
    path: '/admin/corporate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContactsRoute =
  AuthenticatedAdminContactsRouteImport.update({
    id: '/admin/contacts',
    path: '/admin/contacts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/admin/bookings',
    path: '/admin/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/admin/backup',
    path: '/admin/backup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAiAssistantRoute =
  AuthenticatedAdminAiAssistantRouteImport.update({
    id: '/admin/ai-assistant',
    path: '/admin/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvoicesIdRoute =
  AuthenticatedAdminInvoicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminInvoicesRoute,
  } as any)
const AuthenticatedAdminFleetIdRoute =
  AuthenticatedAdminFleetIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminFleetRoute,
  } as any)
const AuthenticatedAdminDriversIdRoute =
  AuthenticatedAdminDriversIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminDriversRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/airport-transfers': typeof PublicAirportTransfersRoute
  '/blog': typeof PublicBlogRouteWithChildren
  '/cancellation': typeof PublicCancellationRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/fleet': typeof PublicFleetRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/refund': typeof PublicRefundRoute
  '/services': typeof PublicServicesRoute
  '/terms': typeof PublicTermsRoute
  '/admin/ai-assistant': typeof AuthenticatedAdminAiAssistantRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/corporate': typeof AuthenticatedAdminCorporateRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRouteWithChildren
  '/admin/errors': typeof AuthenticatedAdminErrorsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/finance-settings': typeof AuthenticatedAdminFinanceSettingsRoute
  '/admin/fleet': typeof AuthenticatedAdminFleetRouteWithChildren
  '/admin/fleet-dashboard': typeof AuthenticatedAdminFleetDashboardRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/whatsapp-templates': typeof AuthenticatedAdminWhatsappTemplatesRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/p/$slug': typeof PublicPSlugRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/drivers/$id': typeof AuthenticatedAdminDriversIdRoute
  '/admin/fleet/$id': typeof AuthenticatedAdminFleetIdRoute
  '/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/airport-transfers': typeof PublicAirportTransfersRoute
  '/blog': typeof PublicBlogRouteWithChildren
  '/cancellation': typeof PublicCancellationRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/fleet': typeof PublicFleetRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy': typeof PublicPrivacyRoute
  '/refund': typeof PublicRefundRoute
  '/services': typeof PublicServicesRoute
  '/terms': typeof PublicTermsRoute
  '/admin/ai-assistant': typeof AuthenticatedAdminAiAssistantRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/corporate': typeof AuthenticatedAdminCorporateRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRouteWithChildren
  '/admin/errors': typeof AuthenticatedAdminErrorsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/finance-settings': typeof AuthenticatedAdminFinanceSettingsRoute
  '/admin/fleet': typeof AuthenticatedAdminFleetRouteWithChildren
  '/admin/fleet-dashboard': typeof AuthenticatedAdminFleetDashboardRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/whatsapp-templates': typeof AuthenticatedAdminWhatsappTemplatesRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/p/$slug': typeof PublicPSlugRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/drivers/$id': typeof AuthenticatedAdminDriversIdRoute
  '/admin/fleet/$id': typeof AuthenticatedAdminFleetIdRoute
  '/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/airport-transfers': typeof PublicAirportTransfersRoute
  '/_public/blog': typeof PublicBlogRouteWithChildren
  '/_public/cancellation': typeof PublicCancellationRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/fleet': typeof PublicFleetRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/refund': typeof PublicRefundRoute
  '/_public/services': typeof PublicServicesRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/admin/ai-assistant': typeof AuthenticatedAdminAiAssistantRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/_authenticated/admin/corporate': typeof AuthenticatedAdminCorporateRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/_authenticated/admin/drivers': typeof AuthenticatedAdminDriversRouteWithChildren
  '/_authenticated/admin/errors': typeof AuthenticatedAdminErrorsRoute
  '/_authenticated/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/finance-settings': typeof AuthenticatedAdminFinanceSettingsRoute
  '/_authenticated/admin/fleet': typeof AuthenticatedAdminFleetRouteWithChildren
  '/_authenticated/admin/fleet-dashboard': typeof AuthenticatedAdminFleetDashboardRoute
  '/_authenticated/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRouteWithChildren
  '/_authenticated/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/_authenticated/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/routes': typeof AuthenticatedAdminRoutesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/whatsapp-templates': typeof AuthenticatedAdminWhatsappTemplatesRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/p/$slug': typeof PublicPSlugRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/drivers/$id': typeof AuthenticatedAdminDriversIdRoute
  '/_authenticated/admin/fleet/$id': typeof AuthenticatedAdminFleetIdRoute
  '/_authenticated/admin/invoices/$id': typeof AuthenticatedAdminInvoicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/about'
    | '/airport-transfers'
    | '/blog'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/fleet'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/services'
    | '/terms'
    | '/admin/ai-assistant'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/contacts'
    | '/admin/corporate'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/dispatch'
    | '/admin/drivers'
    | '/admin/errors'
    | '/admin/expenses'
    | '/admin/faqs'
    | '/admin/finance'
    | '/admin/finance-settings'
    | '/admin/fleet'
    | '/admin/fleet-dashboard'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/invoices'
    | '/admin/maintenance'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/operations'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/payroll'
    | '/admin/pricing'
    | '/admin/promotions'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp-templates'
    | '/blog/$slug'
    | '/p/$slug'
    | '/admin/customers/$id'
    | '/admin/drivers/$id'
    | '/admin/fleet/$id'
    | '/admin/invoices/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/about'
    | '/airport-transfers'
    | '/blog'
    | '/cancellation'
    | '/contact'
    | '/faq'
    | '/fleet'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/services'
    | '/terms'
    | '/admin/ai-assistant'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/categories'
    | '/admin/contacts'
    | '/admin/corporate'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/dispatch'
    | '/admin/drivers'
    | '/admin/errors'
    | '/admin/expenses'
    | '/admin/faqs'
    | '/admin/finance'
    | '/admin/finance-settings'
    | '/admin/fleet'
    | '/admin/fleet-dashboard'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/invoices'
    | '/admin/maintenance'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/operations'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/payroll'
    | '/admin/pricing'
    | '/admin/promotions'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp-templates'
    | '/blog/$slug'
    | '/p/$slug'
    | '/admin/customers/$id'
    | '/admin/drivers/$id'
    | '/admin/fleet/$id'
    | '/admin/invoices/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/auth'
    | '/sitemap.xml'
    | '/_public/about'
    | '/_public/airport-transfers'
    | '/_public/blog'
    | '/_public/cancellation'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/fleet'
    | '/_public/pricing'
    | '/_public/privacy'
    | '/_public/refund'
    | '/_public/services'
    | '/_public/terms'
    | '/_public/'
    | '/_authenticated/admin/ai-assistant'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/contacts'
    | '/_authenticated/admin/corporate'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/dispatch'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/errors'
    | '/_authenticated/admin/expenses'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/finance-settings'
    | '/_authenticated/admin/fleet'
    | '/_authenticated/admin/fleet-dashboard'
    | '/_authenticated/admin/hero'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/maintenance'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/operations'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/payroll'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/promotions'
    | '/_authenticated/admin/refunds'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/routes'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/whatsapp-templates'
    | '/_public/blog/$slug'
    | '/_public/p/$slug'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/drivers/$id'
    | '/_authenticated/admin/fleet/$id'
    | '/_authenticated/admin/invoices/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/refund': {
      id: '/_public/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof PublicRefundRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/fleet': {
      id: '/_public/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof PublicFleetRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cancellation': {
      id: '/_public/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof PublicCancellationRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/airport-transfers': {
      id: '/_public/airport-transfers'
      path: '/airport-transfers'
      fullPath: '/airport-transfers'
      preLoaderRoute: typeof PublicAirportTransfersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/p/$slug': {
      id: '/_public/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PublicPSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicBlogRoute
    }
    '/_authenticated/admin/whatsapp-templates': {
      id: '/_authenticated/admin/whatsapp-templates'
      path: '/admin/whatsapp-templates'
      fullPath: '/admin/whatsapp-templates'
      preLoaderRoute: typeof AuthenticatedAdminWhatsappTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/routes': {
      id: '/_authenticated/admin/routes'
      path: '/admin/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AuthenticatedAdminRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/refunds': {
      id: '/_authenticated/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AuthenticatedAdminRefundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/promotions': {
      id: '/_authenticated/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AuthenticatedAdminPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payroll': {
      id: '/_authenticated/admin/payroll'
      path: '/admin/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AuthenticatedAdminPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/operations': {
      id: '/_authenticated/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AuthenticatedAdminOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/maintenance': {
      id: '/_authenticated/admin/maintenance'
      path: '/admin/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/hero': {
      id: '/_authenticated/admin/hero'
      path: '/admin/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AuthenticatedAdminHeroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fleet-dashboard': {
      id: '/_authenticated/admin/fleet-dashboard'
      path: '/admin/fleet-dashboard'
      fullPath: '/admin/fleet-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminFleetDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fleet': {
      id: '/_authenticated/admin/fleet'
      path: '/admin/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AuthenticatedAdminFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/finance-settings': {
      id: '/_authenticated/admin/finance-settings'
      path: '/admin/finance-settings'
      fullPath: '/admin/finance-settings'
      preLoaderRoute: typeof AuthenticatedAdminFinanceSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/admin/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/expenses': {
      id: '/_authenticated/admin/expenses'
      path: '/admin/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/errors': {
      id: '/_authenticated/admin/errors'
      path: '/admin/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AuthenticatedAdminErrorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/drivers': {
      id: '/_authenticated/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AuthenticatedAdminDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dispatch': {
      id: '/_authenticated/admin/dispatch'
      path: '/admin/dispatch'
      fullPath: '/admin/dispatch'
      preLoaderRoute: typeof AuthenticatedAdminDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/corporate': {
      id: '/_authenticated/admin/corporate'
      path: '/admin/corporate'
      fullPath: '/admin/corporate'
      preLoaderRoute: typeof AuthenticatedAdminCorporateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contacts': {
      id: '/_authenticated/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AuthenticatedAdminContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/admin/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ai-assistant': {
      id: '/_authenticated/admin/ai-assistant'
      path: '/admin/ai-assistant'
      fullPath: '/admin/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAdminAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/invoices/$id': {
      id: '/_authenticated/admin/invoices/$id'
      path: '/$id'
      fullPath: '/admin/invoices/$id'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedAdminInvoicesRoute
    }
    '/_authenticated/admin/fleet/$id': {
      id: '/_authenticated/admin/fleet/$id'
      path: '/$id'
      fullPath: '/admin/fleet/$id'
      preLoaderRoute: typeof AuthenticatedAdminFleetIdRouteImport
      parentRoute: typeof AuthenticatedAdminFleetRoute
    }
    '/_authenticated/admin/drivers/$id': {
      id: '/_authenticated/admin/drivers/$id'
      path: '/$id'
      fullPath: '/admin/drivers/$id'
      preLoaderRoute: typeof AuthenticatedAdminDriversIdRouteImport
      parentRoute: typeof AuthenticatedAdminDriversRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
  }
}

interface AuthenticatedAdminCustomersRouteChildren {
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
}

const AuthenticatedAdminCustomersRouteChildren: AuthenticatedAdminCustomersRouteChildren =
  {
    AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  }

const AuthenticatedAdminCustomersRouteWithChildren =
  AuthenticatedAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminDriversRouteChildren {
  AuthenticatedAdminDriversIdRoute: typeof AuthenticatedAdminDriversIdRoute
}

const AuthenticatedAdminDriversRouteChildren: AuthenticatedAdminDriversRouteChildren =
  {
    AuthenticatedAdminDriversIdRoute: AuthenticatedAdminDriversIdRoute,
  }

const AuthenticatedAdminDriversRouteWithChildren =
  AuthenticatedAdminDriversRoute._addFileChildren(
    AuthenticatedAdminDriversRouteChildren,
  )

interface AuthenticatedAdminFleetRouteChildren {
  AuthenticatedAdminFleetIdRoute: typeof AuthenticatedAdminFleetIdRoute
}

const AuthenticatedAdminFleetRouteChildren: AuthenticatedAdminFleetRouteChildren =
  {
    AuthenticatedAdminFleetIdRoute: AuthenticatedAdminFleetIdRoute,
  }

const AuthenticatedAdminFleetRouteWithChildren =
  AuthenticatedAdminFleetRoute._addFileChildren(
    AuthenticatedAdminFleetRouteChildren,
  )

interface AuthenticatedAdminInvoicesRouteChildren {
  AuthenticatedAdminInvoicesIdRoute: typeof AuthenticatedAdminInvoicesIdRoute
}

const AuthenticatedAdminInvoicesRouteChildren: AuthenticatedAdminInvoicesRouteChildren =
  {
    AuthenticatedAdminInvoicesIdRoute: AuthenticatedAdminInvoicesIdRoute,
  }

const AuthenticatedAdminInvoicesRouteWithChildren =
  AuthenticatedAdminInvoicesRoute._addFileChildren(
    AuthenticatedAdminInvoicesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAiAssistantRoute: typeof AuthenticatedAdminAiAssistantRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminContactsRoute: typeof AuthenticatedAdminContactsRoute
  AuthenticatedAdminCorporateRoute: typeof AuthenticatedAdminCorporateRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRouteWithChildren
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDispatchRoute: typeof AuthenticatedAdminDispatchRoute
  AuthenticatedAdminDriversRoute: typeof AuthenticatedAdminDriversRouteWithChildren
  AuthenticatedAdminErrorsRoute: typeof AuthenticatedAdminErrorsRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminFinanceSettingsRoute: typeof AuthenticatedAdminFinanceSettingsRoute
  AuthenticatedAdminFleetRoute: typeof AuthenticatedAdminFleetRouteWithChildren
  AuthenticatedAdminFleetDashboardRoute: typeof AuthenticatedAdminFleetDashboardRoute
  AuthenticatedAdminHeroRoute: typeof AuthenticatedAdminHeroRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRouteWithChildren
  AuthenticatedAdminMaintenanceRoute: typeof AuthenticatedAdminMaintenanceRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOperationsRoute: typeof AuthenticatedAdminOperationsRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPayrollRoute: typeof AuthenticatedAdminPayrollRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminPromotionsRoute: typeof AuthenticatedAdminPromotionsRoute
  AuthenticatedAdminRefundsRoute: typeof AuthenticatedAdminRefundsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminRoutesRoute: typeof AuthenticatedAdminRoutesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWhatsappTemplatesRoute: typeof AuthenticatedAdminWhatsappTemplatesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAiAssistantRoute: AuthenticatedAdminAiAssistantRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminContactsRoute: AuthenticatedAdminContactsRoute,
  AuthenticatedAdminCorporateRoute: AuthenticatedAdminCorporateRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminCustomersRoute:
    AuthenticatedAdminCustomersRouteWithChildren,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDispatchRoute: AuthenticatedAdminDispatchRoute,
  AuthenticatedAdminDriversRoute: AuthenticatedAdminDriversRouteWithChildren,
  AuthenticatedAdminErrorsRoute: AuthenticatedAdminErrorsRoute,
  AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminFinanceSettingsRoute:
    AuthenticatedAdminFinanceSettingsRoute,
  AuthenticatedAdminFleetRoute: AuthenticatedAdminFleetRouteWithChildren,
  AuthenticatedAdminFleetDashboardRoute: AuthenticatedAdminFleetDashboardRoute,
  AuthenticatedAdminHeroRoute: AuthenticatedAdminHeroRoute,
  AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRouteWithChildren,
  AuthenticatedAdminMaintenanceRoute: AuthenticatedAdminMaintenanceRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminOperationsRoute: AuthenticatedAdminOperationsRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPayrollRoute: AuthenticatedAdminPayrollRoute,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
  AuthenticatedAdminPromotionsRoute: AuthenticatedAdminPromotionsRoute,
  AuthenticatedAdminRefundsRoute: AuthenticatedAdminRefundsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminRoutesRoute: AuthenticatedAdminRoutesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWhatsappTemplatesRoute:
    AuthenticatedAdminWhatsappTemplatesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicBlogRouteChildren {
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
}

const PublicBlogRouteChildren: PublicBlogRouteChildren = {
  PublicBlogSlugRoute: PublicBlogSlugRoute,
}

const PublicBlogRouteWithChildren = PublicBlogRoute._addFileChildren(
  PublicBlogRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAirportTransfersRoute: typeof PublicAirportTransfersRoute
  PublicBlogRoute: typeof PublicBlogRouteWithChildren
  PublicCancellationRoute: typeof PublicCancellationRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicFleetRoute: typeof PublicFleetRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicRefundRoute: typeof PublicRefundRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPSlugRoute: typeof PublicPSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicAirportTransfersRoute: PublicAirportTransfersRoute,
  PublicBlogRoute: PublicBlogRouteWithChildren,
  PublicCancellationRoute: PublicCancellationRoute,
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicFleetRoute: PublicFleetRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicRefundRoute: PublicRefundRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicPSlugRoute: PublicPSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
